### ISSUE TITLE
Open All in Tabs duplicates

### ISSUE THREAD

**Issue by AndrewNeo** [AndrewNeo/faextender#46]
Have gotten multiple reports, will investigate.

**Comment by seedylifestyle** [comment]
Awesome!  So glad you are still supporting the addon! I find it essential.  I wrote you an email on this, but I'll repeat here: 

Root cause I believe is a change to FA UI where there is now html on the page to support description text on top of the thumbnail when you hover over with a mouse.  As a result, there is an <a href="/view/#######/"> for both the thumbnail and the overlay. Since the extension is simply looking for that pattern, we get the doubles.

It does look like jquery offers an easy way to remove duplicates (http://stackoverflow.com/questions/2822962/jquery-remove-duplicate-elements)  so perhaps that could be the fix?

Maybe there is a smarter way to work around this, but I am not really a skilled coder and something like this should continue to prevent dupes upon future UI changes.   Hope it helps!

**Comment by shadistiger** [comment]
Yeah in the loop to open the links I just put in a test to see if the link in question has a tittle attribute or not. Then set it up to not open then ones that do.   Not sure how efficient that is, but it works for me :)  See how long it is before FA changes things again and messes that up!

**Comment by KorblFuchs** [comment]
Changing to this in OpenInTabs.js works well for me.
// Collect all view page links
var tabLinks = jQuery("a[href*='/view/'][title]");

**Comment by AndrewNeo** [comment]
Update submitted to AMO.
